package csc289Hmwk1;

public enum CMinusDFAState {
	//KEY STATES
	ST_START,
	ST_DONE,
	ST_INID, ST_INNUM, ST_ERROR, ST_ASSIGN,
	//2 CHAR OPERATORS, aka DECISION STATES
	ST_ASSIGN_OR_EQ, ST_LT_OR_LTOE, ST_GT_OR_GTOE,
	ST_DIV_OR_COMMENT, ST_ENTER_COMMENT, ST_NESTED_COMMENT, ST_ENDCOMMENT,
	//MATH
	ST_PLUS, ST_MINUS, ST_MULTIPLY, ST_DIVIDE,
	//COMPARISON OPERATORS
	ST_EQ, ST_NEQ,
	ST_LE, ST_GE, 
	//SYNTAX
	ST_LP, ST_RP, ST_LSB, ST_RSB, ST_SCBRACE, ST_LCBRACE, ST_SEMICOLON, ST_COMMA
}
